Issue / Nuxt 3/ Layout
mouseless/learn-nuxt pull request #26
Opened 2023-03-01 15:28 UTC by alptuncs

Learn how to add layout

## Tasks

- [ ] Create a layout
- [ ] Add layout doc section

2023-03-01 21:38 UTC, cihandeniz commented on .theme/components/Layout.vue
> +    class="sticky-top"
sticky vb class kasma hic, tepede dumduz iki link olsun yeter. tek amacimiz layout kullanimini demonstrate etmek

2023-03-01 21:41 UTC, cihandeniz commented on .theme/pages/[...content-page].vue
> +      <Layout />
en bastan yanlis gitmeyelim, layout yapisini ogrenip uygulayalim
:point_right: https://nuxt.com/docs/guide/directory-structure/layouts

learn reposu ya, yeni ogreniyor olman lazim ;)

2023-03-02 11:57 UTC, cihandeniz requested changes

2023-03-02 11:57 UTC, cihandeniz commented on .theme/layouts/default.vue
> +      <nav class="App__nav">
bu class'lar neden var, gerekli miymis? kaldirsak ne olur?

2023-03-02 11:57 UTC, cihandeniz commented on .theme/app.vue
> +  <NuxtLayout :name="layout">
`:name="layout"` ne anlama geliyor, layout adinda bir layout yok, default adinda layout var ya, bunu hic koymasak otomatik `default.vue` yu kullanmiyor mu?

2023-03-02 11:57 UTC, cihandeniz commented on .theme/layouts/default.vue
> +        <router-link to="/">
ben `<NuxtLink>` var diye biliyorum, onu kullansak daha dogru olmaz mi?

2023-03-02 11:57 UTC, cihandeniz commented on .theme/layouts/default.vue
> +        <router-link to="/">
bunu base url acikken test ettiniz mi? ekliyor mu baseurl'i?

2023-03-02 11:57 UTC, cihandeniz commented on .theme/layouts/default.vue
> +      <router-view />
`router-view` fazla gibi geldi, `slot` zaten verilen ic kismin cizildigi yer degil mi? `router-view` ne ciziyor?

2023-03-02 11:57 UTC, cihandeniz commented on .theme/layouts/default.vue
> +        </router-link>
bu link'leri tek tek vermek yerine `<ContentQuery>` ile otomatik yapalim derim, yeni markdown geldikce buraya cizsin... her sayfa ekledigimizde bir de burayi maintain etmeyelim...

2023-03-02 11:57 UTC, cihandeniz commented on .theme/layouts/default.vue
> +        </router-link>
content query ile yalnizca kok folder'daki markdown'lari cekebilirsin

2023-03-02 11:57 UTC, cihandeniz commented on .theme/layouts/default.vue
> +      <slot />
`slot`'u neden `header` altina ciziyoruz, page content'i header'a cizmis oldun su an. div altindaki header'da navigation var, onun yanina (sibling) olarak slot'u cizebiliriz direkt

2023-03-02 12:08 UTC, cihandeniz commented on .theme/layouts/default.vue
> +      <nav class="App__nav">
bir de ek is yazayim aklima geldi.  nav'dan once mouseless logosu ile nuxt logosunu yan yana koyalim diyorum. en tepede yan yana, ornek :point_down: 

<img src="https://raw.githubusercontent.com/mouseless/brand/main/assets/logo/svg/logo-mark-primary.svg" height="10" /> | <img src="https://nuxt.com/assets/design-kit/logo/icon-green.svg" height="10" />

2023-03-02 13:14 UTC, SeferMirza approved these changes

2023-03-02 13:35 UTC, cihandeniz approved these changes
@SeferMirza ayri pr'da devam edecek

2023-03-02 13:36 UTC, merged